filename pulse "/folders/myfolders/pulse.dat";

DATA C;
INFILE pulse;
INPUT ROW PULSE1 PULSE2 RAN SMOKES SEX HEIGHT WEIGHT ACTIVITY;
DIFF = PULSE2-PULSE1;
RUN;

PROC TTEST DATA=C;
CLASS SEX;
VAR DIFF;
RUN;

PROC TTEST DATA=C;
CLASS SMOKES;
VAR DIFF;
RUN;
